name: Execute tests after push
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
    
    # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
          
    # Library Cache
      - name: Cache              
        uses: actions/cache@v4.0.1
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
    # Tests      
      - name: Run tests
        uses: game-ci/unity-test-runner@v4.1.1
        id: myTestStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.7f1
          projectPath: ./
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+GameRules,+GameView'

      - name: Upload tests coverage
        uses: actions/upload-artifact@v4.3.1
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.myTestStep.outputs.coveragePath }}
          
      # Build
      - name: Build
        uses: game-ci/unity-builder@v4.2.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          versioning: Semantic
          
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: Build
          path: build
